export const SHOW_SLIDER_IMAGES = 'SHOW_SLIDER_IMAGES';
export const UPDATE_CURRENT_SLIDE = 'UPDATE_CURRENT_SLIDE';
export const SHOW_BANNER_IMAGES = 'SHOW_BANNER_IMAGES';
export const SHOW_GENRE_IMAGES = 'SHOW_GENRE_IMAGES';
export const NEXT_PREV_BUTTON = 'NEXT_PREV_BUTTON';
export const CREATE_URL = 'CREATE_URL';
export const SHOW_MOVIES_TITLES = 'SHOW_MOVIES_TITLES';
export const SHOW_MOVIES_CATEGORIES = 'SHOW_MOVIES_CATEGORIES';
export const SHOW_FILMS = 'SHOW_FILMS';

